server:
  port: 8761

eureka:
  instance:
    hostname: bankati-discovery.onrender.com
  client:
    serviceUrl:
      defaultZone:
        ${EUREKA_HOST:https://bankati-discovery.onrender.com/eureka/}
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false